name: 'spark_dbt_delta_lake'
version: '1.0.0'
config-version: 2

profile: 'spark_dbt_delta_lake'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  spark_dbt_delta_lake:
    +materialized: table
    +file_format: delta

vars:
  raw_data_path: "{{ env_var('DBT_RAW_DATA_PATH', 'data/raw') }}"
  processed_data_path: "{{ env_var('DBT_PROCESSED_DATA_PATH', 'data/processed') }}"